require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rn_fair_bill' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'Permission-Calendars', :path => "../node_modules/react-native-permissions/ios/Calendars"
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera"
  pod 'Permission-Contacts', :path => "../node_modules/react-native-permissions/ios/Contacts"
  pod 'Permission-FaceID', :path => "../node_modules/react-native-permissions/ios/FaceID"
  pod 'Permission-PhotoLibrary', :path => "../node_modules/react-native-permissions/ios/PhotoLibrary"

  target 'rn_fair_billTests' do
    
    inherit! :complete
    # Pods for testing
    
    pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
      'TextDetector',
      'FaceDetectorMLKit',
     'BarcodeDetectorMLKit'
    ]
    pod 'react-native-contacts', :path => '../node_modules/react-native-contacts' 
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end